version: '3.8'

services:
  app:
    build: .
    container_name: welearnsecshop-app
    ports:
      - "8086:80"
    volumes:
      - ./welearnsecshop:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: welearnsecshop-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: welearnsecshop
      MYSQL_USER: welearnsec
      MYSQL_PASSWORD: welearnsecpass
    volumes:
      - db_data:/var/lib/mysql
      - ./welearnsecshop/db/db.sql:/docker-entrypoint-initdb.d/db.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: welearnsecshop-pma
    restart: always
    ports:
      - "8087:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass

volumes:
  db_data:
